
const RATE_DATA = [
  // AIRPORTS
  {city:"JFK – John F. Kennedy",region:"Airports",price:110},
  {city:"LaGuardia Airport",region:"Airports",price:90},
  {city:"Newark Liberty Airport",region:"Airports",price:120},
  {city:"Teterboro Airport",region:"Airports",price:125},
  {city:"Westchester County Airport",region:"Airports",price:182},
  {city:"Morristown Airport",region:"Airports",price:160},

  // CONNECTICUT
  {city:"Amesville",region:"Connecticut",price:372},
  {city:"Ansonia",region:"Connecticut",price:295},
  {city:"Avon",region:"Connecticut",price:389},
  {city:"Bantam",region:"Connecticut",price:360},
  {city:"Belltown",region:"Connecticut",price:172},
  {city:"Berlin",region:"Connecticut",price:363},
  {city:"Bethel",region:"Connecticut",price:271},
  {city:"Bloomfield",region:"Connecticut",price:397},
  {city:"Bolton",region:"Connecticut",price:411},
  {city:"Botsford",region:"Connecticut",price:290},
  {city:"Branchville",region:"Connecticut",price:240},
  {city:"Bransford",region:"Connecticut",price:311},
  {city:"Bridgeport",region:"Connecticut",price:265},
  {city:"Bridgewater",region:"Connecticut",price:317},
  {city:"Bristol",region:"Connecticut",price:363},
  {city:"Brookfield",region:"Connecticut",price:295},
  {city:"Brookfield Center",region:"Connecticut",price:295},
  {city:"Burlington",region:"Connecticut",price:385},
  {city:"Byram",region:"Connecticut",price:141},
  {city:"Canaan",region:"Connecticut",price:475},
  {city:"Cannadale",region:"Connecticut",price:246},
  {city:"Canton",region:"Connecticut",price:398},
  {city:"Cheshire",region:"Connecticut",price:331},
  {city:"Clinton",region:"Connecticut",price:349},
  {city:"Colchester",region:"Connecticut",price:451},
  {city:"Colebrook",region:"Connecticut",price:421},
  {city:"Cornwall",region:"Connecticut",price:430},
  {city:"Cos Cob",region:"Connecticut",price:150},
  {city:"Cromwell",region:"Connecticut",price:363},
  {city:"Danbury",region:"Connecticut",price:276},
  {city:"Danielson",region:"Connecticut",price:495},
  {city:"Darien",region:"Connecticut",price:172},
  {city:"Deep River",region:"Connecticut",price:416},
  {city:"Derby",region:"Connecticut",price:285},
  {city:"Devon",region:"Connecticut",price:246},
  {city:"Donaldson",region:"Connecticut",price:228},
  {city:"Durham",region:"Connecticut",price:336},
  {city:"East Haddam",region:"Connecticut",price:466},
  {city:"East Hartford",region:"Connecticut",price:394},
  {city:"East Haven",region:"Connecticut",price:301},
  {city:"East Norwalk",region:"Connecticut",price:194},
  {city:"Easton",region:"Connecticut",price:251},
  {city:"Ellington",region:"Connecticut",price:427},
  {city:"Enfield",region:"Connecticut",price:426},
  {city:"Essex",region:"Connecticut",price:411},
  {city:"Fair Haven",region:"Connecticut",price:300},
  {city:"Fair Village",region:"Connecticut",price:377},
  {city:"Fairfield",region:"Connecticut",price:244},
  {city:"Falls Village",region:"Connecticut",price:377},
  {city:"Farmington",region:"Connecticut",price:377},
  {city:"Gaylordville",region:"Connecticut",price:385},
  {city:"Georgetown",region:"Connecticut",price:237},
  {city:"Glastonbury",region:"Connecticut",price:397},
  {city:"Glenbrook",region:"Connecticut",price:176},
  {city:"Glenville",region:"Connecticut",price:150},
  {city:"Goshen",region:"Connecticut",price:411},
  {city:"Granby",region:"Connecticut",price:411},
  {city:"Green Farms",region:"Connecticut",price:220},
  {city:"Greenwich",region:"Connecticut",price:144},
  {city:"Groton",region:"Connecticut",price:438},
  {city:"Guilford",region:"Connecticut",price:317},
  {city:"Hamden",region:"Connecticut",price:311},
  {city:"Hartford",region:"Connecticut",price:394},
  {city:"Higganum",region:"Connecticut",price:404},
  {city:"High Ridge",region:"Connecticut",price:226},
  {city:"Huntington",region:"Connecticut",price:277},
  {city:"Kensington",region:"Connecticut",price:371},
  {city:"Kent",region:"Connecticut",price:376},
  {city:"Killingworth",region:"Connecticut",price:371},
  {city:"Lakeville",region:"Connecticut",price:437},
  {city:"Litchfield",region:"Connecticut",price:398},
  {city:"Long Ridge",region:"Connecticut",price:189},
  {city:"Lordship",region:"Connecticut",price:276},
  {city:"Lyme",region:"Connecticut",price:422},
  {city:"Madison",region:"Connecticut",price:327},
  {city:"Manchester",region:"Connecticut",price:398},
  {city:"Marlborough",region:"Connecticut",price:410},
  {city:"Meads Corner",region:"Connecticut",price:155},
  {city:"Meridian",region:"Connecticut",price:347},
  {city:"Mianus",region:"Connecticut",price:152},
  {city:"Middlebury",region:"Connecticut",price:361},
  {city:"Middletown",region:"Connecticut",price:366},
  {city:"Milford",region:"Connecticut",price:276},
  {city:"Monroe",region:"Connecticut",price:285},
  {city:"Moodus",region:"Connecticut",price:534},
  {city:"Mystic",region:"Connecticut",price:474},
  {city:"Naugatuck",region:"Connecticut",price:340},
  {city:"New Britain",region:"Connecticut",price:377},
  {city:"New Canaan",region:"Connecticut",price:201},
  {city:"New Fairfield",region:"Connecticut",price:285},
  {city:"New Haven",region:"Connecticut",price:300},
  {city:"New London",region:"Connecticut",price:431},
  {city:"New Milford",region:"Connecticut",price:317},
  {city:"New Preston",region:"Connecticut",price:363},
  {city:"Newington",region:"Connecticut",price:427},
  {city:"Newtown",region:"Connecticut",price:295},
  {city:"Niantic",region:"Connecticut",price:426},
  {city:"Norfolk",region:"Connecticut",price:421},
  {city:"Noroton",region:"Connecticut",price:168},
  {city:"North Canton",region:"Connecticut",price:437},
  {city:"North Haven",region:"Connecticut",price:322},
  {city:"Northville",region:"Connecticut",price:345},
  {city:"Norton Heights",region:"Connecticut",price:182},
  {city:"Norwalk",region:"Connecticut",price:174},
  {city:"Norwich",region:"Connecticut",price:451},
  {city:"Old Greenwich",region:"Connecticut",price:156},
  {city:"Old Lyme",region:"Connecticut",price:422},
  {city:"Old Saybrook",region:"Connecticut",price:398},
  {city:"Orange",region:"Connecticut",price:295},
  {city:"Oxford",region:"Connecticut",price:315},
  {city:"Plainfield",region:"Connecticut",price:476},
  {city:"Plainville",region:"Connecticut",price:402},
  {city:"Pomfret",region:"Connecticut",price:493},
  {city:"Putnam",region:"Connecticut",price:507},
  {city:"Quaker Ridge",region:"Connecticut",price:149},
  {city:"Redding",region:"Connecticut",price:255},
  {city:"Redding Ridge",region:"Connecticut",price:263},
  {city:"Ridgefield",region:"Connecticut",price:230},
  {city:"Riverside",region:"Connecticut",price:152},
  {city:"Rockville",region:"Connecticut",price:422},
  {city:"Rocky Hill",region:"Connecticut",price:382},
  {city:"Round Hill",region:"Connecticut",price:155},
  {city:"Rowayton",region:"Connecticut",price:194},
  {city:"Roxbury",region:"Connecticut",price:317},
  {city:"Salisbury",region:"Connecticut",price:415},
  {city:"Sandy Hook",region:"Connecticut",price:290},
  {city:"Saugatuck",region:"Connecticut",price:200},
  {city:"Savin Rock",region:"Connecticut",price:276},
  {city:"Shelton",region:"Connecticut",price:285},
  {city:"Sherman",region:"Connecticut",price:355},
  {city:"Silvermine",region:"Connecticut",price:196},
  {city:"Simsbury",region:"Connecticut",price:411},
  {city:"South Norwalk",region:"Connecticut",price:195},
  {city:"Southbury",region:"Connecticut",price:304},
  {city:"Southington",region:"Connecticut",price:360},
  {city:"Southport",region:"Connecticut",price:226},
  {city:"Springdale",region:"Connecticut",price:172},
  {city:"Stafford Springs",region:"Connecticut",price:475},
  {city:"Stamford",region:"Connecticut",price:164},
  {city:"Stanwich",region:"Connecticut",price:165},
  {city:"Stepney",region:"Connecticut",price:257},
  {city:"Stonington",region:"Connecticut",price:475},
  {city:"Storrs",region:"Connecticut",price:458},
  {city:"Stratford",region:"Connecticut",price:270},
  {city:"Suffield",region:"Connecticut",price:431},
  {city:"Thomaston",region:"Connecticut",price:371},
  {city:"Thompsonville",region:"Connecticut",price:447},
  {city:"Tolland",region:"Connecticut",price:426},
  {city:"Torrington",region:"Connecticut",price:411},
  {city:"Trumbull",region:"Connecticut",price:271},
  {city:"Union City",region:"Connecticut",price:336},
  {city:"Upper Stepney",region:"Connecticut",price:317},
  {city:"Vernon",region:"Connecticut",price:411},
  {city:"Voluntown",region:"Connecticut",price:471},
  {city:"Wallingford",region:"Connecticut",price:331},
  {city:"Warren",region:"Connecticut",price:376},
  {city:"Washington",region:"Connecticut",price:358},
  {city:"Washington Depot",region:"Connecticut",price:360},
  {city:"Waterbury",region:"Connecticut",price:345},
  {city:"Waterford",region:"Connecticut",price:427},
  {city:"Watertown",region:"Connecticut",price:355},
  {city:"Wethersfield",region:"Connecticut",price:386},
  {city:"Wilton",region:"Connecticut",price:220},
  {city:"Windham",region:"Connecticut",price:439},
  {city:"Windsor",region:"Connecticut",price:411},
  {city:"Windsor Locks",region:"Connecticut",price:416},
  {city:"Winsted",region:"Connecticut",price:402},
  {city:"Wolcott",region:"Connecticut",price:389},
  {city:"Woodbridge",region:"Connecticut",price:300},
  {city:"Woodbury",region:"Connecticut",price:330},
  {city:"Woodmont",region:"Connecticut",price:283},
  {city:"Yantic",region:"Connecticut",price:469},

  // LONG ISLAND
  {city:"Albertson",region:"Long Island",price:110},
  {city:"Amagansett",region:"Long Island",price:411},
  {city:"Amityville",region:"Long Island",price:171},
  {city:"Asharoken",region:"Long Island",price:190},
  {city:"Atlantic Beach",region:"Long Island",price:124},
  {city:"Babylon",region:"Long Island",price:185},
  {city:"Baldwin",region:"Long Island",price:131},
  {city:"Bay Park",region:"Long Island",price:124},
  {city:"Bay Port",region:"Long Island",price:207},
  {city:"Bay Shore",region:"Long Island",price:189},
  {city:"Bayville",region:"Long Island",price:158},
  {city:"Bellmore",region:"Long Island",price:141},
  {city:"Bellport",region:"Long Island",price:226},
  {city:"Bellrose",region:"Long Island",price:110},
  {city:"Bethpage",region:"Long Island",price:144},
  {city:"Blue Point",region:"Long Island",price:210},
  {city:"Bohemia",region:"Long Island",price:212},
  {city:"Brentwood",region:"Long Island",price:196},
  {city:"Bridgehampton",region:"Long Island",price:383},
  {city:"Brightwaters",region:"Long Island",price:189},
  {city:"Brookhaven",region:"Long Island",price:271},
  {city:"Brookville",region:"Long Island",price:135},
  {city:"Carle Place",region:"Long Island",price:121},
  {city:"Cedarhurst",region:"Long Island",price:110},
  {city:"Center Moriches",region:"Long Island",price:266},
  {city:"Centereach",region:"Long Island",price:200},
  {city:"Centerport",region:"Long Island",price:171},
  {city:"Central Islip",region:"Long Island",price:182},
  {city:"Centre Island",region:"Long Island",price:168},
  {city:"Cold Spring Harbor",region:"Long Island",price:172},
  {city:"Commack",region:"Long Island",price:190},
  {city:"Copiague",region:"Long Island",price:176},
  {city:"Coram",region:"Long Island",price:234},
  {city:"Cove Neck",region:"Long Island",price:165},
  {city:"Cutchogue",region:"Long Island",price:322},
  {city:"Deer Park",region:"Long Island",price:180},
  {city:"Dix Hills",region:"Long Island",price:171},
  {city:"East Hampton",region:"Long Island",price:402},
  {city:"East Hills",region:"Long Island",price:130},
  {city:"East Islip",region:"Long Island",price:196},
  {city:"East Marion",region:"Long Island",price:366},
  {city:"East Meadow",region:"Long Island",price:134},
  {city:"East Moriches",region:"Long Island",price:268},
  {city:"East Northport",region:"Long Island",price:190},
  {city:"East Norwich",region:"Long Island",price:149},
  {city:"East Patchogue",region:"Long Island",price:207},
  {city:"East Rockaway",region:"Long Island",price:124},
  {city:"East Setauket",region:"Long Island",price:209},
  {city:"East Williston",region:"Long Island",price:113},
  {city:"Eatons Neck",region:"Long Island",price:194},
  {city:"Elmont",region:"Long Island",price:116},
  {city:"Elwood",region:"Long Island",price:172},
  {city:"Farmingdale",region:"Long Island",price:158},
  {city:"Farmingville",region:"Long Island",price:200},
  {city:"Fire Island",region:"Long Island",price:201},
  {city:"Floral Park",region:"Long Island",price:116},
  {city:"Flower Hill",region:"Long Island",price:110},
  {city:"Freeport",region:"Long Island",price:134},
  {city:"Garden City",region:"Long Island",price:122},
  {city:"Glen Cove",region:"Long Island",price:135},
  {city:"Glen Head",region:"Long Island",price:128},
  {city:"Glenwood Landing",region:"Long Island",price:133},
  {city:"Great Neck",region:"Long Island",price:110},
  {city:"Great River",region:"Long Island",price:200},
  {city:"Greenlawn",region:"Long Island",price:168},
  {city:"Greenport",region:"Long Island",price:360},
  {city:"Greenvale",region:"Long Island",price:120},
  {city:"Hauppauge",region:"Long Island",price:186},
  {city:"Hempstead",region:"Long Island",price:122},
  {city:"Hewlett",region:"Long Island",price:116},
  {city:"Hicksville",region:"Long Island",price:135},
  {city:"Holbrook",region:"Long Island",price:228},
  {city:"Holtsville",region:"Long Island",price:200},
  {city:"Huntington",region:"Long Island",price:172},
  {city:"Huntington Bay",region:"Long Island",price:182},
  {city:"Huntington Station",region:"Long Island",price:172},
  {city:"Inwood",region:"Long Island",price:110},
  {city:"Island Park",region:"Long Island",price:135},
  {city:"Islip",region:"Long Island",price:186},
  {city:"Islip Terrace",region:"Long Island",price:189},
  {city:"Jamesport",region:"Long Island",price:304},
  {city:"Jericho",region:"Long Island",price:135},
  {city:"Jones Beach",region:"Long Island",price:158},
  {city:"Kings Park",region:"Long Island",price:194},
  {city:"Kings Point",region:"Long Island",price:110},
  {city:"Lake Grove",region:"Long Island",price:201},
  {city:"Lake Ronkonkoma",region:"Long Island",price:196},
  {city:"Lake Success",region:"Long Island",price:110},
  {city:"Lakeview",region:"Long Island",price:110},
  {city:"Laurel",region:"Long Island",price:310},
  {city:"Laurel Hollow",region:"Long Island",price:158},
  {city:"Lawrence",region:"Long Island",price:110},
  {city:"Levittown",region:"Long Island",price:134},
  {city:"Lido Beach",region:"Long Island",price:136},
  {city:"Lindenhurst",region:"Long Island",price:182},
  {city:"Lloyd Neck",region:"Long Island",price:180},
  {city:"Locust Valley",region:"Long Island",price:149},
  {city:"Long Beach",region:"Long Island",price:136},
  {city:"Lynbrook",region:"Long Island",price:116},
  {city:"MacArthur Airport",region:"Long Island",price:207},
  {city:"Malverne",region:"Long Island",price:110},
  {city:"Manhasset",region:"Long Island",price:120},
  {city:"Manorville",region:"Long Island",price:274},
  {city:"Massapequa",region:"Long Island",price:158},
  {city:"Massapequa Park",region:"Long Island",price:165},
  {city:"Mastic",region:"Long Island",price:254},
  {city:"Mastic Beach",region:"Long Island",price:263},
  {city:"Matinecock",region:"Long Island",price:144},
  {city:"Mattituck",region:"Long Island",price:315},
  {city:"Medford",region:"Long Island",price:207},
  {city:"Melville",region:"Long Island",price:150},
  {city:"Merrick",region:"Long Island",price:134},
  {city:"Middle Island",region:"Long Island",price:226},
  {city:"Mill Neck",region:"Long Island",price:156},
  {city:"Miller Place",region:"Long Island",price:228},
  {city:"Mineola",region:"Long Island",price:120},
  {city:"Montauk",region:"Long Island",price:439},
  {city:"Montauk Point",region:"Long Island",price:452},
  {city:"Moriches",region:"Long Island",price:255},
  {city:"Mount Sinai",region:"Long Island",price:228},
  {city:"Nesconset",region:"Long Island",price:195},
  {city:"New Hyde Park",region:"Long Island",price:110},
  {city:"North Bellmore",region:"Long Island",price:135},
  {city:"North Haven",region:"Long Island",price:383},
  {city:"North Hills",region:"Long Island",price:110},
  {city:"North Merrick",region:"Long Island",price:135},
  {city:"Northport",region:"Long Island",price:176},
  {city:"Oak Beach",region:"Long Island",price:200},
  {city:"Oakdale",region:"Long Island",price:196},
  {city:"Ocean Beach",region:"Long Island",price:246},
  {city:"Oceanside",region:"Long Island",price:130},
  {city:"Old Bethpage",region:"Long Island",price:149},
  {city:"Old Brookville",region:"Long Island",price:124},
  {city:"Old Field",region:"Long Island",price:216},
  {city:"Old Westbury",region:"Long Island",price:124},
  {city:"Orient",region:"Long Island",price:386},
  {city:"Orient Point",region:"Long Island",price:397},
  {city:"Oyster Bay",region:"Long Island",price:158},
  {city:"Oyster Bay Cove",region:"Long Island",price:180},
  {city:"Patchogue",region:"Long Island",price:212},
  {city:"Peconic",region:"Long Island",price:331},
  {city:"Plainedge",region:"Long Island",price:141},
  {city:"Plainview",region:"Long Island",price:136},
  {city:"Plandome",region:"Long Island",price:110},
  {city:"Point Lookout",region:"Long Island",price:135},
  {city:"Port Jefferson",region:"Long Island",price:220},
  {city:"Port Washington",region:"Long Island",price:122},
  {city:"Quogue",region:"Long Island",price:317},
  {city:"Riverhead",region:"Long Island",price:283},
  {city:"Rockville Centre",region:"Long Island",price:130},
  {city:"Rocky Point",region:"Long Island",price:241},
  {city:"Roosevelt",region:"Long Island",price:131},
  {city:"Roslyn",region:"Long Island",price:120},
  {city:"Roslyn Harbor",region:"Long Island",price:122},
  {city:"Roslyn Heights",region:"Long Island",price:110},
  {city:"Sag Harbor",region:"Long Island",price:372},
  {city:"Sagaponak",region:"Long Island",price:385},
  {city:"Saint James",region:"Long Island",price:195},
  {city:"San Remo",region:"Long Island",price:195},
  {city:"Sands Point",region:"Long Island",price:135},
  {city:"Sayville",region:"Long Island",price:207},
  {city:"Seaford",region:"Long Island",price:147},
  {city:"Selden",region:"Long Island",price:210},
  {city:"Setauket",region:"Long Island",price:212},
  {city:"Shelter Island",region:"Long Island",price:391},
  {city:"Shinnecock Hills",region:"Long Island",price:345},
  {city:"Shirley",region:"Long Island",price:241},
  {city:"Shoreham",region:"Long Island",price:246},
  {city:"Smithtown",region:"Long Island",price:200},
  {city:"Sound Beach",region:"Long Island",price:230},
  {city:"Southampton",region:"Long Island",price:363},
  {city:"Southold",region:"Long Island",price:340},
  {city:"Speonk",region:"Long Island",price:285},
  {city:"Springs",region:"Long Island",price:415},
  {city:"Stony Brook",region:"Long Island",price:210},
  {city:"Syosset",region:"Long Island",price:152},
  {city:"Terryville",region:"Long Island",price:210},
  {city:"Three Mile Harbor",region:"Long Island",price:411},
  {city:"Tiana",region:"Long Island",price:330},
  {city:"Tuckahoe",region:"Long Island",price:361},
  {city:"Uniondale",region:"Long Island",price:124},
  {city:"Upper Brookville",region:"Long Island",price:141},
  {city:"Upton",region:"Long Island",price:230},
  {city:"Valley Stream",region:"Long Island",price:116},
  {city:"Wading River",region:"Long Island",price:254},
  {city:"Wainscott",region:"Long Island",price:391},
  {city:"Wantagh",region:"Long Island",price:129},
  {city:"Water Mill",region:"Long Island",price:371},
  {city:"West Hampton",region:"Long Island",price:345},
  {city:"West Hempstead",region:"Long Island",price:122},
  {city:"West Islip",region:"Long Island",price:183},
  {city:"West Sayville",region:"Long Island",price:209},
  {city:"Westbury",region:"Long Island",price:124},
  {city:"Williston Park",region:"Long Island",price:110},
  {city:"Woodbury",region:"Long Island",price:149},
  {city:"Woodmere",region:"Long Island",price:116},
  {city:"Wyandanch",region:"Long Island",price:171},
  {city:"Yaphank",region:"Long Island",price:226},

  // NEW JERSEY
  {city:"Aberdeen",region:"New Jersey",price:165},
  {city:"Absecon",region:"New Jersey",price:448},
  {city:"Allamuchy",region:"New Jersey",price:255},
  {city:"Allendale",region:"New Jersey",price:144},
  {city:"Allenhurst",region:"New Jersey",price:220},
  {city:"Allentown",region:"New Jersey",price:255},
  {city:"Allenwood",region:"New Jersey",price:237},
  {city:"Alpine",region:"New Jersey",price:117},
  {city:"Andover",region:"New Jersey",price:250},
  {city:"Asbury Park",region:"New Jersey",price:228},
  {city:"Atlantic City",region:"New Jersey",price:448},
  {city:"Atlantic Highlands",region:"New Jersey",price:195},
  {city:"Avalon",region:"New Jersey",price:517},
  {city:"Avenel",region:"New Jersey",price:124},
  {city:"Avon by the Sea",region:"New Jersey",price:237},
  {city:"Barnegat",region:"New Jersey",price:366},
  {city:"Barnegat Light",region:"New Jersey",price:408},
  {city:"Basking Ridge",region:"New Jersey",price:176},
  {city:"Bay Head",region:"New Jersey",price:250},
  {city:"Bayonne",region:"New Jersey",price:92},
  {city:"Bayville",region:"New Jersey",price:295},
  {city:"Beach Haven",region:"New Jersey",price:426},
  {city:"Beachwood",region:"New Jersey",price:295},
  {city:"Bedminster",region:"New Jersey",price:189},
  {city:"Belford",region:"New Jersey",price:186},
  {city:"Belle Mead",region:"New Jersey",price:209},
  {city:"Belleville",region:"New Jersey",price:105},
  {city:"Belmar",region:"New Jersey",price:239},
  {city:"Bergenfield",region:"New Jersey",price:113},
  {city:"Berkeley Heights",region:"New Jersey",price:141},
  {city:"Berlin",region:"New Jersey",price:358},
  {city:"Bernardsville",region:"New Jersey",price:180},
  {city:"Blairstown",region:"New Jersey",price:266},
  {city:"Bloomfield",region:"New Jersey",price:109},
  {city:"Bloomingdale",region:"New Jersey",price:152},
  {city:"Bloomsbury",region:"New Jersey",price:266},
  {city:"Bogota",region:"New Jersey",price:100},
  {city:"Boonton",region:"New Jersey",price:176},
  {city:"Bordentown",region:"New Jersey",price:255},
  {city:"Bound Brook",region:"New Jersey",price:168},
  {city:"Bradley Beach",region:"New Jersey",price:239},
  {city:"Branchburg",region:"New Jersey",price:189},
  {city:"Branchville",region:"New Jersey",price:270},
  {city:"Brick",region:"New Jersey",price:242},
  {city:"Bridgewater",region:"New Jersey",price:180},
  {city:"Brielle",region:"New Jersey",price:237},
  {city:"Brigantine",region:"New Jersey",price:442},
  {city:"Browns Mills",region:"New Jersey",price:317},
  {city:"Burlington",region:"New Jersey",price:295},
  {city:"Butler",region:"New Jersey",price:155},
  {city:"Caldwell",region:"New Jersey",price:130},
  {city:"Camden",region:"New Jersey",price:351},
  {city:"Cape May",region:"New Jersey",price:558},
  {city:"Cape May Courthouse",region:"New Jersey",price:568},
  {city:"Carlstadt",region:"New Jersey",price:107},
  {city:"Carteret",region:"New Jersey",price:120},
  {city:"Cassville",region:"New Jersey",price:250},
  {city:"Cedar Grove",region:"New Jersey",price:128},
  {city:"Cedar Knolls",region:"New Jersey",price:158},
  {city:"Chatham",region:"New Jersey",price:131},
  {city:"Cherry Hill",region:"New Jersey",price:336},
  {city:"Chester",region:"New Jersey",price:194},
  {city:"Cinnaminson",region:"New Jersey",price:330},
  {city:"Clark",region:"New Jersey",price:124},
  {city:"Cliffside Park",region:"New Jersey",price:89},
  {city:"Clifton",region:"New Jersey",price:113},
  {city:"Clinton",region:"New Jersey",price:239},
  {city:"Closter",region:"New Jersey",price:121},
  {city:"Colonia",region:"New Jersey",price:147},
  {city:"Cranbury",region:"New Jersey",price:209},
  {city:"Cranford",region:"New Jersey",price:113},
  {city:"Cresskill",region:"New Jersey",price:107},
  {city:"Dayton",region:"New Jersey",price:182},
  {city:"Deal",region:"New Jersey",price:226},
  {city:"Demarest",region:"New Jersey",price:113},
  {city:"Denville",region:"New Jersey",price:171},
  {city:"Dover",region:"New Jersey",price:182},
  {city:"Dumont",region:"New Jersey",price:113},
  {city:"Dunellen",region:"New Jersey",price:152},
  {city:"East Hanover",region:"New Jersey",price:144},
  {city:"East Orange",region:"New Jersey",price:107},
  {city:"East Rutherford",region:"New Jersey",price:100},
  {city:"East Windsor",region:"New Jersey",price:217},
  {city:"Eatontown",region:"New Jersey",price:195},
  {city:"Edgewater",region:"New Jersey",price:92},
  {city:"Edison",region:"New Jersey",price:149},
  {city:"Egg Harbor City",region:"New Jersey",price:426},
  {city:"Elizabeth",region:"New Jersey",price:98},
  {city:"Elmwood Park",region:"New Jersey",price:121},
  {city:"Emerson",region:"New Jersey",price:124},
  {city:"Englewood",region:"New Jersey",price:98},
  {city:"Englewood Cliffs",region:"New Jersey",price:91},
  {city:"Englishtown",region:"New Jersey",price:195},
  {city:"Essex Falls",region:"New Jersey",price:113},
  {city:"Ewing",region:"New Jersey",price:255},
  {city:"Fair Haven",region:"New Jersey",price:189},
  {city:"Fairfield",region:"New Jersey",price:131},
  {city:"Fairlawn",region:"New Jersey",price:124},
  {city:"Fanwood",region:"New Jersey",price:131},
  {city:"Far Hills",region:"New Jersey",price:185},
  {city:"Flemington",region:"New Jersey",price:234},
  {city:"Florence",region:"New Jersey",price:276},
  {city:"Florham Park",region:"New Jersey",price:141},
  {city:"Fords",region:"New Jersey",price:136},
  {city:"Forked River",region:"New Jersey",price:336},
  {city:"Fort Lee",region:"New Jersey",price:92},
  {city:"Franklin Lakes",region:"New Jersey",price:144},
  {city:"Franklin Park",region:"New Jersey",price:182},
  {city:"Freehold",region:"New Jersey",price:197},
  {city:"Frenchtown",region:"New Jersey",price:244},
  {city:"Glassboro",region:"New Jersey",price:386},
  {city:"Glen Ridge",region:"New Jersey",price:113},
  {city:"Glen Rock",region:"New Jersey",price:130},
  {city:"Hackensack",region:"New Jersey",price:113},
  {city:"Hackettstown",region:"New Jersey",price:241},
  {city:"Haddonfield",region:"New Jersey",price:336},
  {city:"Haledon",region:"New Jersey",price:141},
  {city:"Hamburg",region:"New Jersey",price:226},
  {city:"Hamilton",region:"New Jersey",price:237},
  {city:"Hammonton",region:"New Jersey",price:366},
  {city:"Harrington Park",region:"New Jersey",price:124},
  {city:"Harrison",region:"New Jersey",price:92},
  {city:"Hasbrouck Heights",region:"New Jersey",price:113},
  {city:"Haskell",region:"New Jersey",price:155},
  {city:"Haworth",region:"New Jersey",price:120},
  {city:"Hawthorne",region:"New Jersey",price:133},
  {city:"Hazlet",region:"New Jersey",price:158},
  {city:"Highland Park",region:"New Jersey",price:158},
  {city:"Highlands",region:"New Jersey",price:200},
  {city:"Hightstown",region:"New Jersey",price:210},
  {city:"Hillsborough",region:"New Jersey",price:213},
  {city:"Hillsdale",region:"New Jersey",price:134},
  {city:"Hillside",region:"New Jersey",price:105},
  {city:"Hoboken",region:"New Jersey",price:81},
  {city:"Hohokus",region:"New Jersey",price:141},
  {city:"Holmdel",region:"New Jersey",price:186},
  {city:"Hopatcong",region:"New Jersey",price:207},
  {city:"Hopewell",region:"New Jersey",price:217},
  {city:"Iselin",region:"New Jersey",price:133},
  {city:"Island Heights",region:"New Jersey",price:285},
  {city:"Jackson",region:"New Jersey",price:266},
  {city:"Jamesburg",region:"New Jersey",price:201},
  {city:"Jersey City",region:"New Jersey",price:81},
  {city:"Keansburg",region:"New Jersey",price:168},
  {city:"Kearny",region:"New Jersey",price:95},
  {city:"Kenilworth",region:"New Jersey",price:110},
  {city:"Keyport",region:"New Jersey",price:158},
  {city:"Kingston",region:"New Jersey",price:185},
  {city:"Kinnelon",region:"New Jersey",price:158},
  {city:"Lake Hiawatha",region:"New Jersey",price:161},
  {city:"Lakewood",region:"New Jersey",price:237},
  {city:"Lambertville",region:"New Jersey",price:255},
  {city:"Lanoka Harbor",region:"New Jersey",price:330},
  {city:"Laurence Harbor",region:"New Jersey",price:158},
  {city:"Lawrence",region:"New Jersey",price:212},
  {city:"Lawrenceville",region:"New Jersey",price:212},
  {city:"Lebanon",region:"New Jersey",price:226},
  {city:"Leonia",region:"New Jersey",price:95},
  {city:"Lincoln Park",region:"New Jersey",price:141},
  {city:"Lincroft",region:"New Jersey",price:182},
  {city:"Linden",region:"New Jersey",price:109},
  {city:"Linwood",region:"New Jersey",price:448},
  {city:"Little Falls",region:"New Jersey",price:124},
  {city:"Little Ferry",region:"New Jersey",price:105},
  {city:"Little Silver",region:"New Jersey",price:197},
  {city:"Livingston",region:"New Jersey",price:124},
  {city:"Lodi",region:"New Jersey",price:113},
  {city:"Long Branch",region:"New Jersey",price:201},
  {city:"Long Valley",region:"New Jersey",price:226},
  {city:"Longport",region:"New Jersey",price:426},
  {city:"Madison",region:"New Jersey",price:135},
  {city:"Mahwah",region:"New Jersey",price:158},
  {city:"Manahawkin",region:"New Jersey",price:366},
  {city:"Manalapan",region:"New Jersey",price:189},
  {city:"Manasquan",region:"New Jersey",price:237},
  {city:"Manchester",region:"New Jersey",price:295},
  {city:"Mantoloking",region:"New Jersey",price:244},
  {city:"Mantua",region:"New Jersey",price:408},
  {city:"Manville",region:"New Jersey",price:185},
  {city:"Maple Shade",region:"New Jersey",price:336},
  {city:"Maplewood",region:"New Jersey",price:120},
  {city:"Margate City",region:"New Jersey",price:426},
  {city:"Marlboro",region:"New Jersey",price:189},
  {city:"Marlton",region:"New Jersey",price:336},
  {city:"Martinsville",region:"New Jersey",price:182},
  {city:"Matawan",region:"New Jersey",price:164},
  {city:"Mays Landing",region:"New Jersey",price:421},
  {city:"Maywood",region:"New Jersey",price:120},
  {city:"Medford",region:"New Jersey",price:341},
  {city:"Mendham",region:"New Jersey",price:168},
  {city:"Metuchen",region:"New Jersey",price:141},
  {city:"Middletown",region:"New Jersey",price:182},
  {city:"Midland Park",region:"New Jersey",price:136},
  {city:"Millburn",region:"New Jersey",price:121},
  {city:"Millstone",region:"New Jersey",price:195},
  {city:"Milltown",region:"New Jersey",price:183},
  {city:"Millville",region:"New Jersey",price:487},
  {city:"Monmouth Beach",region:"New Jersey",price:207},
  {city:"Monmouth Junction",region:"New Jersey",price:180},
  {city:"Montclair",region:"New Jersey",price:120},
  {city:"Montvale",region:"New Jersey",price:144},
  {city:"Montville",region:"New Jersey",price:167},
  {city:"Moorestown",region:"New Jersey",price:330},
  {city:"Morristown",region:"New Jersey",price:160},
  {city:"Mount Arlington",region:"New Jersey",price:200},
  {city:"Mount Holly",region:"New Jersey",price:306},
  {city:"Mount Laurel",region:"New Jersey",price:327},
  {city:"Mountain Lakes",region:"New Jersey",price:167},
  {city:"Mountainside",region:"New Jersey",price:121},
  {city:"Murray Hill",region:"New Jersey",price:135},
  {city:"Neptune",region:"New Jersey",price:228},
  {city:"Netcong",region:"New Jersey",price:210},
  {city:"New Brunswick",region:"New Jersey",price:158},
  {city:"New Milford",region:"New Jersey",price:121},
  {city:"New Providence",region:"New Jersey",price:135},
  {city:"Newark",region:"New Jersey",price:121},
  {city:"Newark Airport",region:"New Jersey",price:121},
  {city:"Newton",region:"New Jersey",price:244},
  {city:"North Arlington",region:"New Jersey",price:98},
  {city:"North Bergen",region:"New Jersey",price:81},
  {city:"North Branch",region:"New Jersey",price:186},
  {city:"North Brunswick",region:"New Jersey",price:176},
  {city:"North Caldwell",region:"New Jersey",price:124},
  {city:"North Haledon",region:"New Jersey",price:144},
  {city:"North Wildwood",region:"New Jersey",price:529},
  {city:"Northvale",region:"New Jersey",price:133},
  {city:"Norwood",region:"New Jersey",price:121},
  {city:"Nutley",region:"New Jersey",price:105},
  {city:"Oakhurst",region:"New Jersey",price:201},
  {city:"Oakland",region:"New Jersey",price:152},
  {city:"Ocean City",region:"New Jersey",price:468},
  {city:"Ocean Grove",region:"New Jersey",price:226},
  {city:"Old Bridge",region:"New Jersey",price:158},
  {city:"Oradell",region:"New Jersey",price:124},
  {city:"Orange",region:"New Jersey",price:110},
  {city:"Ortley Beach",region:"New Jersey",price:266},
  {city:"Paramus",region:"New Jersey",price:124},
  {city:"Park Ridge",region:"New Jersey",price:136},
  {city:"Parlin",region:"New Jersey",price:149},
  {city:"Passaic",region:"New Jersey",price:107},
  {city:"Paulsborough",region:"New Jersey",price:416},
  {city:"Peapack",region:"New Jersey",price:190},
  {city:"Pennington",region:"New Jersey",price:234},
  {city:"Pennsauken",region:"New Jersey",price:347},
  {city:"Pequannock",region:"New Jersey",price:144},
  {city:"Perth Amboy",region:"New Jersey",price:141},
  {city:"Piscataway",region:"New Jersey",price:161},
  {city:"Pittstown",region:"New Jersey",price:244},
  {city:"Plainfield",region:"New Jersey",price:147},
  {city:"Plainsboro",region:"New Jersey",price:207},
  {city:"Point Pleasant",region:"New Jersey",price:239},
  {city:"Pompton Lakes",region:"New Jersey",price:150},
  {city:"Pompton Plains",region:"New Jersey",price:150},
  {city:"Princeton",region:"New Jersey",price:213},
  {city:"Rahway",region:"New Jersey",price:124},
  {city:"Ramsey",region:"New Jersey",price:152},
  {city:"Randolph",region:"New Jersey",price:183},
  {city:"Raritan",region:"New Jersey",price:185},
  {city:"Red Bank",region:"New Jersey",price:189},
  {city:"Ridgefield",region:"New Jersey",price:100},
  {city:"Ridgefield Park",region:"New Jersey",price:100},
  {city:"Ridgewood",region:"New Jersey",price:135},
  {city:"Ringwood",region:"New Jersey",price:190},
  {city:"Rio Grande",region:"New Jersey",price:547},
  {city:"River Edge",region:"New Jersey",price:117},
  {city:"Riverdale",region:"New Jersey",price:147},
  {city:"Riverton",region:"New Jersey",price:327},
  {city:"Rivervale",region:"New Jersey",price:134},
  {city:"Robbinsville",region:"New Jersey",price:237},
  {city:"Rochelle Park",region:"New Jersey",price:124},
  {city:"Rockaway",region:"New Jersey",price:182},
  {city:"Roseland",region:"New Jersey",price:124},
  {city:"Roselle",region:"New Jersey",price:109},
  {city:"Roselle Park",region:"New Jersey",price:109},
  {city:"Rumson",region:"New Jersey",price:195},
  {city:"Rutherford",region:"New Jersey",price:100},
  {city:"Saddle Brook",region:"New Jersey",price:110},
  {city:"Saddle River",region:"New Jersey",price:141},
  {city:"Salem",region:"New Jersey",price:448},
  {city:"Sayreville",region:"New Jersey",price:155},
  {city:"Scotch Plains",region:"New Jersey",price:135},
  {city:"Sea Bright",region:"New Jersey",price:234},
  {city:"Sea Isle City",region:"New Jersey",price:476},
  {city:"Secaucus",region:"New Jersey",price:95},
  {city:"Ship Bottom",region:"New Jersey",price:408},
  {city:"Short Hills",region:"New Jersey",price:121},
  {city:"Shrewsbury",region:"New Jersey",price:190},
  {city:"Silverton",region:"New Jersey",price:244},
  {city:"Skillman",region:"New Jersey",price:221},
  {city:"Smithville",region:"New Jersey",price:386},
  {city:"Somers Point",region:"New Jersey",price:468},
  {city:"Somerset",region:"New Jersey",price:165},
  {city:"Somerville",region:"New Jersey",price:180},
  {city:"South Amboy",region:"New Jersey",price:144},
  {city:"South Orange",region:"New Jersey",price:121},
  {city:"South Plainfield",region:"New Jersey",price:152},
  {city:"South River",region:"New Jersey",price:158},
  {city:"Sparta",region:"New Jersey",price:228},
  {city:"Spotswood",region:"New Jersey",price:168},
  {city:"Spring Lake",region:"New Jersey",price:237},
  {city:"Springfield",region:"New Jersey",price:120},
  {city:"Stanhope",region:"New Jersey",price:216},
  {city:"Stillwater",region:"New Jersey",price:276},
  {city:"Stirling",region:"New Jersey",price:144},
  {city:"Succasunna",region:"New Jersey",price:189},
  {city:"Summit",region:"New Jersey",price:124},
  {city:"Sussex",region:"New Jersey",price:237},
  {city:"Teaneck",region:"New Jersey",price:107},
  {city:"Tenafly",region:"New Jersey",price:110},
  {city:"Teterboro",region:"New Jersey",price:113},
  {city:"Tinton Falls",region:"New Jersey",price:197},
  {city:"Titusville",region:"New Jersey",price:266},
  {city:"Toms River",region:"New Jersey",price:285},
  {city:"Totowa",region:"New Jersey",price:135},
  {city:"Towaco",region:"New Jersey",price:158},
  {city:"Trenton",region:"New Jersey",price:244},
  {city:"Tuckerton",region:"New Jersey",price:386},
  {city:"Union",region:"New Jersey",price:113},
  {city:"Union Beach",region:"New Jersey",price:165},
  {city:"Union City",region:"New Jersey",price:74},
  {city:"Upper Montclair",region:"New Jersey",price:113},
  {city:"Verona",region:"New Jersey",price:135},
  {city:"Villas",region:"New Jersey",price:580},
  {city:"Vineland",region:"New Jersey",price:461},
  {city:"Waldwick",region:"New Jersey",price:141},
  {city:"Wall Township",region:"New Jersey",price:228},
  {city:"Wallington",region:"New Jersey",price:109},
  {city:"Wanaque",region:"New Jersey",price:156},
  {city:"Wantage",region:"New Jersey",price:244},
  {city:"Waretown",region:"New Jersey",price:327},
  {city:"Warren",region:"New Jersey",price:176},
  {city:"Washington",region:"New Jersey",price:257},
  {city:"Washington Township",region:"New Jersey",price:144},
  {city:"Watchung",region:"New Jersey",price:147},
  {city:"Wayne",region:"New Jersey",price:136},
  {city:"Weehawken",region:"New Jersey",price:81},
  {city:"West Caldwell",region:"New Jersey",price:134},
  {city:"West Long Branch",region:"New Jersey",price:207},
  {city:"West Milford",region:"New Jersey",price:207},
  {city:"West New York",region:"New Jersey",price:81},
  {city:"West Orange",region:"New Jersey",price:117},
  {city:"West Windsor",region:"New Jersey",price:212},
  {city:"Westfield",region:"New Jersey",price:136},
  {city:"Westwood",region:"New Jersey",price:133},
  {city:"Wharton",region:"New Jersey",price:176},
  {city:"Whippany",region:"New Jersey",price:158},
  {city:"Whitehouse",region:"New Jersey",price:216},
  {city:"Whiting",region:"New Jersey",price:285},
  {city:"Wildwood",region:"New Jersey",price:547},
  {city:"Wildwood Crest",region:"New Jersey",price:547},
  {city:"Woodbridge",region:"New Jersey",price:133},
  {city:"Woodbury",region:"New Jersey",price:372},
  {city:"Woodcliff Lake",region:"New Jersey",price:144},
  {city:"Wyckoff",region:"New Jersey",price:144},
  {city:"Yardville",region:"New Jersey",price:255},

  // NEW YORK
  {city:"Accord",region:"New York",price:371},
  {city:"Airmont",region:"New York",price:167},
  {city:"Albany",region:"New York",price:529},
  {city:"Amenia",region:"New York",price:363},
  {city:"Amity",region:"New York",price:237},
  {city:"Amsterdam",region:"New York",price:646},
  {city:"Ancram",region:"New York",price:426},
  {city:"Arden",region:"New York",price:212},
  {city:"Arlington",region:"New York",price:317},
  {city:"Auburn",region:"New York",price:1024},
  {city:"Baldwin Place",region:"New York",price:228},
  {city:"Ballston Spa",region:"New York",price:593},
  {city:"Bardonia",region:"New York",price:158},
  {city:"Barrytown",region:"New York",price:386},
  {city:"Barryville",region:"New York",price:363},
  {city:"Batavia",region:"New York",price:1236},
  {city:"Beacon",region:"New York",price:271},
  {city:"Bear Mountain",region:"New York",price:212},
  {city:"Bearsville",region:"New York",price:404},
  {city:"Beaverkill",region:"New York",price:448},
  {city:"Beekman",region:"New York",price:276},
  {city:"Bellvale",region:"New York",price:210},
  {city:"Bethel",region:"New York",price:394},
  {city:"Big Indian",region:"New York",price:447},
  {city:"Binghamton",region:"New York",price:602},
  {city:"Blauvelt",region:"New York",price:141},
  {city:"Blooming Grove",region:"New York",price:255},
  {city:"Bloomingburg",region:"New York",price:294},
  {city:"Brewster",region:"New York",price:255},
  {city:"Brockport",region:"New York",price:1245},
  {city:"Buffalo",region:"New York",price:1346},
  {city:"Cairo",region:"New York",price:447},
  {city:"Callicoon",region:"New York",price:430},
  {city:"Callicoon Center",region:"New York",price:438},
  {city:"Campbell Hall",region:"New York",price:257},
  {city:"Canajoharie",region:"New York",price:669},
  {city:"Carmel",region:"New York",price:255},
  {city:"Catskill",region:"New York",price:427},
  {city:"Centenary",region:"New York",price:172},
  {city:"Central Village",region:"New York",price:226},
  {city:"Chelsea",region:"New York",price:287},
  {city:"Chester",region:"New York",price:244},
  {city:"Chichester",region:"New York",price:422},
  {city:"Circleville",region:"New York",price:301},
  {city:"Clarkstown",region:"New York",price:152},
  {city:"Claryville",region:"New York",price:427},
  {city:"Claverack",region:"New York",price:427},
  {city:"Clermont",region:"New York",price:397},
  {city:"Clinton Corners",region:"New York",price:331},
  {city:"Clintondale",region:"New York",price:330},
  {city:"Cobleskill",region:"New York",price:624},
  {city:"Cohoes",region:"New York",price:411},
  {city:"Cold Spring",region:"New York",price:242},
  {city:"Colonie",region:"New York",price:718},
  {city:"Congers",region:"New York",price:171},
  {city:"Continental Village",region:"New York",price:220},
  {city:"Cooperstown",region:"New York",price:771},
  {city:"Copake",region:"New York",price:402},
  {city:"Corning",region:"New York",price:803},
  {city:"Cornwall",region:"New York",price:250},
  {city:"Cornwall on Hudson",region:"New York",price:254},
  {city:"Cortland",region:"New York",price:710},
  {city:"Coxsackie",region:"New York",price:466},
  {city:"Craigsville",region:"New York",price:250},
  {city:"Craryville",region:"New York",price:431},
  {city:"Crawford",region:"New York",price:330},
  {city:"Delhi",region:"New York",price:521},
  {city:"Delmar",region:"New York",price:507},
  {city:"Denning",region:"New York",price:439},
  {city:"Deposit",region:"New York",price:536},
  {city:"Dover Plains",region:"New York",price:340},
  {city:"Dunkirk",region:"New York",price:1509},
  {city:"Durham",region:"New York",price:461},
  {city:"Eagle Valley",region:"New York",price:201},
  {city:"East Chatham",region:"New York",price:466},
  {city:"East Fishkill",region:"New York",price:283},
  {city:"East Jewett",region:"New York",price:431},
  {city:"East Park",region:"New York",price:331},
  {city:"East Walden",region:"New York",price:290},
  {city:"Eddyville",region:"New York",price:360},
  {city:"Eldred",region:"New York",price:382},
  {city:"Elmira",region:"New York",price:734},
  {city:"Elizaville",region:"New York",price:383},
  {city:"Ellenville",region:"New York",price:340},
  {city:"Endicott",region:"New York",price:608},
  {city:"Esopus",region:"New York",price:341},
  {city:"Fallsburgh",region:"New York",price:386},
  {city:"Ferndale",region:"New York",price:404},
  {city:"Fishkill",region:"New York",price:276},
  {city:"Fleischmans",region:"New York",price:458},
  {city:"Florida",region:"New York",price:283},
  {city:"Fonda",region:"New York",price:608},
  {city:"Fort Montgomery",region:"New York",price:226},
  {city:"Glens Falls",region:"New York",price:661},
  {city:"Gloversville",region:"New York",price:294},
  {city:"Goshen",region:"New York",price:263},
  {city:"Grahamsville",region:"New York",price:425},
  {city:"Grandview on Hudson",region:"New York",price:135},
  {city:"Greenfield Park",region:"New York",price:330},
  {city:"Greenville",region:"New York",price:330},
  {city:"Greenwood Lake",region:"New York",price:217},
  {city:"Grossinger",region:"New York",price:411},
  {city:"Haines Falls",region:"New York",price:416},
  {city:"Harriman",region:"New York",price:221},
  {city:"Haverstraw",region:"New York",price:195},
  {city:"Hempstead",region:"New York",price:171},
  {city:"Herkimer",region:"New York",price:734},
  {city:"High Falls",region:"New York",price:376},
  {city:"High View",region:"New York",price:300},
  {city:"Highland",region:"New York",price:323},
  {city:"Highland Falls",region:"New York",price:254},
  {city:"Highland Mills",region:"New York",price:230},
  {city:"Hillburn",region:"New York",price:171},
  {city:"Hillcrest",region:"New York",price:171},
  {city:"Holmes",region:"New York",price:300},
  {city:"Hoosick Falls",region:"New York",price:593},
  {city:"Hopewell Junction",region:"New York",price:287},
  {city:"Hornell",region:"New York",price:782},
  {city:"Hudson",region:"New York",price:431},
  {city:"Hudson Falls",region:"New York",price:661},
  {city:"Huguenot",region:"New York",price:327},
  {city:"Hunter",region:"New York",price:430},
  {city:"Hurleyville",region:"New York",price:397},
  {city:"Hyde Park",region:"New York",price:330},
  {city:"Ithaca",region:"New York",price:715},
  {city:"Jeffersonville",region:"New York",price:427},
  {city:"Jewett",region:"New York",price:457},
  {city:"Johnson City",region:"New York",price:619},
  {city:"Johnstown",region:"New York",price:641},
  {city:"Jones Point",region:"New York",price:216},
  {city:"Kingston",region:"New York",price:376},
  {city:"LaGrange",region:"New York",price:266},
  {city:"LaGrangeville",region:"New York",price:300},
  {city:"Lake Carmel",region:"New York",price:270},
  {city:"Lake George",region:"New York",price:700},
  {city:"Lake Hill",region:"New York",price:404},
  {city:"Lake Katrine",region:"New York",price:377},
  {city:"Lake Luzerne",region:"New York",price:653},
  {city:"Lake Mahopac",region:"New York",price:237},
  {city:"Lake Oscawana",region:"New York",price:239},
  {city:"Lake Peekskill",region:"New York",price:230},
  {city:"Lake Placid",region:"New York",price:977},
  {city:"Lakeville",region:"New York",price:195},
  {city:"Lanesville",region:"New York",price:430},
  {city:"Latham",region:"New York",price:532},
  {city:"Leeds",region:"New York",price:424},
  {city:"Liberty",region:"New York",price:411},
  {city:"Lincoln Park",region:"New York",price:371},
  {city:"Little Falls",region:"New York",price:747},
  {city:"Livingston Manor",region:"New York",price:431},
  {city:"Lloyd",region:"New York",price:333},
  {city:"Lockport",region:"New York",price:1393},
  {city:"Loomis",region:"New York",price:416},
  {city:"Maybrook",region:"New York",price:283},
  {city:"Medina",region:"New York",price:1331},
  {city:"Middletown",region:"New York",price:283},
  {city:"Milan",region:"New York",price:345},
  {city:"Millbrook",region:"New York",price:333},
  {city:"Millerton",region:"New York",price:394},
  {city:"Milton",region:"New York",price:287},
  {city:"Modena",region:"New York",price:304},
  {city:"Monticello",region:"New York",price:376},
  {city:"Monroe",region:"New York",price:227},
  {city:"Monsey",region:"New York",price:167},
  {city:"Montgomery",region:"New York",price:287},
  {city:"Mount Hope",region:"New York",price:301},
  {city:"Mount Ivy",region:"New York",price:194},
  {city:"Mount Marion",region:"New York",price:397},
  {city:"Mount Tremper",region:"New York",price:411},
  {city:"Mountaindale",region:"New York",price:363},
  {city:"Nanuet",region:"New York",price:152},
  {city:"Narrowsburg",region:"New York",price:408},
  {city:"Nelsonville",region:"New York",price:244},
  {city:"New City",region:"New York",price:171},
  {city:"New Hamburg",region:"New York",price:287},
  {city:"New Hampton",region:"New York",price:266},
  {city:"New Hempstead",region:"New York",price:172},
  {city:"New Hurley",region:"New York",price:294},
  {city:"New Milford",region:"New York",price:241},
  {city:"New Paltz",region:"New York",price:327},
  {city:"New Windsor",region:"New York",price:257},
  {city:"Newburgh",region:"New York",price:281},
  {city:"Niagara Falls",region:"New York",price:1423},
  {city:"North Branch",region:"New York",price:431},
  {city:"North Brewster",region:"New York",price:266},
  {city:"Norwich",region:"New York",price:705},
  {city:"Nyack",region:"New York",price:149},
  {city:"Old Chatham",region:"New York",price:513},
  {city:"Olean",region:"New York",price:1087},
  {city:"Olive Bridge",region:"New York",price:408},
  {city:"Oneida",region:"New York",price:842},
  {city:"Oneonta",region:"New York",price:612},
  {city:"Orangeburg",region:"New York",price:224},
  {city:"Oswego",region:"New York",price:668},
  {city:"Oxford",region:"New York",price:204},
  {city:"Palisades",region:"New York",price:131},
  {city:"Parksville",region:"New York",price:421},
  {city:"Patterson",region:"New York",price:290},
  {city:"Pearl River",region:"New York",price:144},
  {city:"Phoenicia",region:"New York",price:420},
  {city:"Piermont",region:"New York",price:135},
  {city:"Pine Bush",region:"New York",price:310},
  {city:"Pine Hill",region:"New York",price:240},
  {city:"Pine Island",region:"New York",price:250},
  {city:"Pine Plains",region:"New York",price:386},
  {city:"Plattekill",region:"New York",price:276},
  {city:"Plattsburgh",region:"New York",price:1024},
  {city:"Pleasant Valley",region:"New York",price:330},
  {city:"Pomona",region:"New York",price:194},
  {city:"Port Ewen",region:"New York",price:371},
  {city:"Port Jervis",region:"New York",price:317},
  {city:"Poughkeepsie",region:"New York",price:317},
  {city:"Poughquag",region:"New York",price:300},
  {city:"Putnam Lake",region:"New York",price:270},
  {city:"Putnam Valley",region:"New York",price:226},
  {city:"Quaker Hill",region:"New York",price:311},
  {city:"Ravena",region:"New York",price:493},
  {city:"Red Hook",region:"New York",price:382},
  {city:"Rensselaer",region:"New York",price:509},
  {city:"Rhinebeck",region:"New York",price:349},
  {city:"Rifton",region:"New York",price:341},
  {city:"Rochester",region:"New York",price:1194},
  {city:"Rock Hill",region:"New York",price:340},
  {city:"Rock Tavern",region:"New York",price:268},
  {city:"Rome",region:"New York",price:826},
  {city:"Roscoe",region:"New York",price:447},
  {city:"Rosendale",region:"New York",price:383},
  {city:"Ruby",region:"New York",price:389},
  {city:"Sloatsburg",region:"New York",price:180},
  {city:"Spring Valley",region:"New York",price:164},
  {city:"Suffern",region:"New York",price:167},
  {city:"Tappan",region:"New York",price:134},
  {city:"Tivoli",region:"New York",price:389},
  {city:"Tomkins Cove",region:"New York",price:210},
  {city:"Tompkins Corners",region:"New York",price:241},
  {city:"Towners",region:"New York",price:276},
  {city:"Troy",region:"New York",price:536},
  {city:"Tupper Lake",region:"New York",price:979},
  {city:"Tuxedo Park",region:"New York",price:195},
  {city:"Ulster Park",region:"New York",price:386},
  {city:"Union Center",region:"New York",price:322},
  {city:"Unionville",region:"New York",price:271},
  {city:"Upper Nyack",region:"New York",price:155},
  {city:"Utica",region:"New York",price:774},
  {city:"Vails Gate",region:"New York",price:254},
  {city:"Valley Cottage",region:"New York",price:158},
  {city:"Verbank",region:"New York",price:330},
  {city:"Vestal",region:"New York",price:608},
  {city:"Viola",region:"New York",price:171},
  {city:"Walden",region:"New York",price:294},
  {city:"Walker Valley",region:"New York",price:322},
  {city:"Wallkill",region:"New York",price:283},
  {city:"Wappingers Falls",region:"New York",price:283},
  {city:"Warrensburg",region:"New York",price:726},
  {city:"Warwick",region:"New York",price:241},
  {city:"Washingtonville",region:"New York",price:251},
  {city:"Watertown",region:"New York",price:1122},
  {city:"Watervliet",region:"New York",price:532},
  {city:"Wawarsing",region:"New York",price:371},
  {city:"West Camp",region:"New York",price:382},
  {city:"West Cornwall",region:"New York",price:250},
  {city:"West Haverstraw",region:"New York",price:197},
  {city:"West Hurley",region:"New York",price:386},
  {city:"West Nyack",region:"New York",price:149},
  {city:"West Park",region:"New York",price:336},
  {city:"West Point",region:"New York",price:240},
  {city:"West Shokan",region:"New York",price:310},
  {city:"Westtown",region:"New York",price:271},
  {city:"White Lake",region:"New York",price:404},
  {city:"Windham",region:"New York",price:476},
  {city:"Wingdale",region:"New York",price:317},
  {city:"Woodbourne",region:"New York",price:394},
  {city:"Woodridge",region:"New York",price:376},
  {city:"Woodstock",region:"New York",price:400},
  {city:"Youngsville",region:"New York",price:424},
  {city:"Yulan",region:"New York",price:376},

  // WESTCHESTER
  {city:"Amawalk",region:"Westchester",price:207},
  {city:"Annsville",region:"Westchester",price:207},
  {city:"Ardsley",region:"Westchester",price:121},
  {city:"Armonk",region:"Westchester",price:155},
  {city:"Arrowood",region:"Westchester",price:136},
  {city:"Banksville",region:"Westchester",price:180},
  {city:"Bedford",region:"Westchester",price:186},
  {city:"Bedford Hills",region:"Westchester",price:186},
  {city:"Bedford Village",region:"Westchester",price:185},
  {city:"Briarcliff Manor",region:"Westchester",price:155},
  {city:"Bronxville",region:"Westchester",price:120},
  {city:"Buchanan",region:"Westchester",price:194},
  {city:"Chappaqua",region:"Westchester",price:165},
  {city:"Cortland",region:"Westchester",price:196},
  {city:"Crestwood",region:"Westchester",price:110},
  {city:"Cross River",region:"Westchester",price:216},
  {city:"Croton",region:"Westchester",price:165},
  {city:"Croton Falls",region:"Westchester",price:226},
  {city:"Croton Heights",region:"Westchester",price:194},
  {city:"Croton Lakes",region:"Westchester",price:186},
  {city:"Croton on Hudson",region:"Westchester",price:172},
  {city:"Dobbs Ferry",region:"Westchester",price:120},
  {city:"Dunwoodie",region:"Westchester",price:113},
  {city:"East Chester",region:"Westchester",price:120},
  {city:"Elmsford",region:"Westchester",price:130},
  {city:"Fleetwood",region:"Westchester",price:117},
  {city:"Glenville",region:"Westchester",price:130},
  {city:"Goldens Bridge",region:"Westchester",price:216},
  {city:"Granite Springs",region:"Westchester",price:216},
  {city:"Greenburgh",region:"Westchester",price:135},
  {city:"Greenville",region:"Westchester",price:121},
  {city:"Harmon",region:"Westchester",price:161},
  {city:"Harrison",region:"Westchester",price:130},
  {city:"Hartsdale",region:"Westchester",price:128},
  {city:"Hastings on Hudson",region:"Westchester",price:113},
  {city:"Hawthorne",region:"Westchester",price:136},
  {city:"Jefferson Valley",region:"Westchester",price:216},
  {city:"Katonah",region:"Westchester",price:200},
  {city:"Kitchawan",region:"Westchester",price:180},
  {city:"Lake Lincolndale",region:"Westchester",price:220},
  {city:"Larchmont",region:"Westchester",price:120},
  {city:"Lewisboro",region:"Westchester",price:220},
  {city:"Mamaroneck",region:"Westchester",price:121},
  {city:"Millwood",region:"Westchester",price:171},
  {city:"Mohegan Lake",region:"Westchester",price:212},
  {city:"Montrose",region:"Westchester",price:186},
  {city:"Mount Hope",region:"Westchester",price:120},
  {city:"Mount Kisco",region:"Westchester",price:180},
  {city:"Mount Pleasant",region:"Westchester",price:136},
  {city:"Mount Vernon",region:"Westchester",price:105},
  {city:"New Castle",region:"Westchester",price:161},
  {city:"New Rochelle",region:"Westchester",price:120},
  {city:"North Castle",region:"Westchester",price:161},
  {city:"North Salem",region:"Westchester",price:230},
  {city:"North Tarrytown",region:"Westchester",price:134},
  {city:"North White Plains",region:"Westchester",price:131},
  {city:"Ossining",region:"Westchester",price:155},
  {city:"Peekskill",region:"Westchester",price:200},
  {city:"Pelham",region:"Westchester",price:105},
  {city:"Pelham Manor",region:"Westchester",price:105},
  {city:"Pleasantville",region:"Westchester",price:156},
  {city:"Pocantico Hills",region:"Westchester",price:152},
  {city:"Port Chester",region:"Westchester",price:136},
  {city:"Pound Ridge",region:"Westchester",price:212},
  {city:"Purchase",region:"Westchester",price:135},
  {city:"Purdys",region:"Westchester",price:220},
  {city:"Rye",region:"Westchester",price:135},
  {city:"Rye Brook",region:"Westchester",price:136},
  {city:"Salem Center",region:"Westchester",price:228},
  {city:"Scarsdale",region:"Westchester",price:122},
  {city:"Scotts Corners",region:"Westchester",price:210},
  {city:"Shrub Oak",region:"Westchester",price:216},
  {city:"Somers",region:"Westchester",price:220},
  {city:"South Salem",region:"Westchester",price:226},
  {city:"Tarrytown",region:"Westchester",price:131},
  {city:"Thornwood",region:"Westchester",price:150},
  {city:"Tuckahoe",region:"Westchester",price:110},
  {city:"Valhalla",region:"Westchester",price:135},
  {city:"Verplanck",region:"Westchester",price:194},
  {city:"Vista",region:"Westchester",price:216},
  {city:"Waccabuc",region:"Westchester",price:221},
  {city:"West Harrison",region:"Westchester",price:182},
  {city:"White Plains",region:"Westchester",price:128},
  {city:"Yonkers",region:"Westchester",price:105},
  {city:"Yorktown",region:"Westchester",price:207},
  {city:"Yorktown Heights",region:"Westchester",price:200},
  {city:"Westchester Airport",region:"Westchester",price:186},

  // PENNSYLVANIA
  {city:"Airport PHL",region:"Pennsylvania",price:363},
  {city:"Berwyn",region:"Pennsylvania",price:363},
  {city:"Bryn Mawr",region:"Pennsylvania",price:396},
  {city:"Easton",region:"Pennsylvania",price:363},
  {city:"Locust Street",region:"Pennsylvania",price:363},
  {city:"New Hope",region:"Pennsylvania",price:385},
  {city:"Wayne",region:"Pennsylvania",price:363}
];
